### ISSUE TITLE
Rectify dark/light mode text while switching

### ISSUE THREAD

**Issue by ShrutiGossain** [ShrutiGossain/Text-Analyzer#3]
On changing the mode from light to dark, the text still mentions "Activate dark mode". The text has to be rectified and should be changed to "Activate light mode" while switching from light to dark mode.

**Comment by darshitdudhaiya** [comment]
what do you want to do in it. explain those issue clearly

**Comment by ShrutiGossain** [comment]
On changing the mode from light to dark, the text still mentions "Activate dark mode". The text has to be rectified and should be changed to "Activate light mode" while switching from light to dark mode.

**Comment by darshitdudhaiya** [comment]
@ShrutiGossain ok now I understood exactly what was the issue can you assigning to me I would like to contribute in it
